# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the TypeScript project
FROM node:18 AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for npm install
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire source code to the working directory
COPY . .

# Build the project
RUN npm run build

# Stage 2: Run the project
FROM node:18

# Set working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Define environment variables
ENV OPENAI_API_KEY=your-api-key-here
ENV QDRANT_URL=http://localhost:6333

# Start the application
CMD ["node", "build/index.js"]
